In [38]:
import pandas as pd
import seaborn as sns

In [39]:
train_data = pd.read_csv('/content/SalaryData_Test(1).csv')
test_data = pd.read_csv('/content/SalaryData_Train(1).csv')

In [40]:
train_data

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [41]:
test_data

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [42]:
print(train_data.shape)
print(test_data.shape)

(15060, 14)
(30161, 14)


In [43]:
sorted(train_data['Salary'].unique())

[' <=50K', ' >50K']

In [44]:
train_data['Salary'].value_counts()

 <=50K    11360
 >50K      3700
Name: Salary, dtype: int64

In [45]:
train_data.drop(['sex','relationship','educationno'],axis=1,inplace=True)
test_data.drop(['sex','relationship','educationno'],axis=1,inplace=True)

In [46]:
train_data.dtypes

age               int64
workclass        object
education        object
maritalstatus    object
occupation       object
race             object
capitalgain       int64
capitalloss       int64
hoursperweek      int64
native           object
Salary           object
dtype: object

In [47]:
test_data.dtypes

age               int64
workclass        object
education        object
maritalstatus    object
occupation       object
race             object
capitalgain       int64
capitalloss       int64
hoursperweek      int64
native           object
Salary           object
dtype: object

In [48]:
print(train_data.isnull().sum())
print()
print(test_data.isnull().sum())

age              0
workclass        0
education        0
maritalstatus    0
occupation       0
race             0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

age              0
workclass        0
education        0
maritalstatus    0
occupation       0
race             0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64


In [49]:
# checking and identifying non-numeric columns (same for both train_data and test_data)
cols = []
for i in train_data.columns:
    if train_data[i].dtype == 'object':
        cols.append(i)
cols

['workclass',
 'education',
 'maritalstatus',
 'occupation',
 'race',
 'native',
 'Salary']

In [50]:
# Label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in cols:
    train_data[i] = le.fit_transform(train_data[i])
    test_data[i] = le.fit_transform(test_data[i])

In [51]:
print(train_data.dtypes)
print()
print(test_data.dtypes)

age              int64
workclass        int64
education        int64
maritalstatus    int64
occupation       int64
race             int64
capitalgain      int64
capitalloss      int64
hoursperweek     int64
native           int64
Salary           int64
dtype: object

age              int64
workclass        int64
education        int64
maritalstatus    int64
occupation       int64
race             int64
capitalgain      int64
capitalloss      int64
hoursperweek     int64
native           int64
Salary           int64
dtype: object


In [52]:
x_train = train_data.drop('Salary',axis=1)
y_train = train_data['Salary']
x_test = test_data.drop('Salary',axis=1)
y_test = test_data['Salary']

In [53]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(x_train,y_train)

GaussianNB()

In [54]:
y_pred = GNB.predict(x_test)

In [55]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)
acc = accuracy_score(y_test,y_pred)

print('confusion matrix: \n',cm)
print('\nclassification report: \n',cr)
print('\naccuracy score: ',acc)

confusion matrix: 
 [[21511  1142]
 [ 5186  2322]]

classification report: 
               precision    recall  f1-score   support

           0       0.81      0.95      0.87     22653
           1       0.67      0.31      0.42      7508

    accuracy                           0.79     30161
   macro avg       0.74      0.63      0.65     30161
weighted avg       0.77      0.79      0.76     30161


accuracy score:  0.7901926328702629


In [56]:
# logistic model
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty='none') # logistic regression with no penalty term in the cost function.
clf.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(penalty='none')

In [57]:
from sklearn.preprocessing import StandardScaler
import numpy as np
scaler = StandardScaler()

In [58]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report, accuracy_score, f1_score

In [59]:
test_pred = clf.predict(x_test)
print('Precision = {:.5f}'.format(precision_score(y_test, test_pred)))
print('Accuracy = {:.5f}'.format(accuracy_score(y_test, test_pred)))

Precision = 0.69927
Accuracy = 0.79294


In [60]:
print('Recall = {:.5f}'.format(recall_score(y_test, test_pred)))
print('F1 score = {:.5f}'.format(f1_score(y_test, test_pred)))

Recall = 0.29515
F1 score = 0.41510


In [61]:
print(confusion_matrix(y_test, test_pred))

[[21700   953]
 [ 5292  2216]]


In [62]:
# KNN model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [63]:
y_pred= knn.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [64]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
cm

array([[19467,  3186],
       [ 2888,  4620]])

In [65]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report, accuracy_score, f1_score
print ('Accuracy:', accuracy_score(y_test, y_pred))
print ('\n clasification report:\n', classification_report(y_test, y_pred))

Accuracy: 0.7986141043068864

 clasification report:
               precision    recall  f1-score   support

           0       0.87      0.86      0.87     22653
           1       0.59      0.62      0.60      7508

    accuracy                           0.80     30161
   macro avg       0.73      0.74      0.73     30161
weighted avg       0.80      0.80      0.80     30161



In [66]:
# DECISION TREE model
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [67]:
y_pred=dtc.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [68]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report, accuracy_score, f1_score
model = DecisionTreeClassifier()
model = model.fit(x_train, y_train)
pred = model.predict(x_test)
print ('Accuracy:', accuracy_score(y_test, pred))
print ('\n clasification report:\n', classification_report(y_test, y_pred))
print ('\n confussion matrix:\n',confusion_matrix(y_test, y_pred))

Accuracy: 0.8084281025164948

 clasification report:
               precision    recall  f1-score   support

           0       0.87      0.87      0.87     22653
           1       0.62      0.61      0.62      7508

    accuracy                           0.81     30161
   macro avg       0.74      0.74      0.74     30161
weighted avg       0.81      0.81      0.81     30161


 confussion matrix:
 [[19796  2857]
 [ 2903  4605]]


In [69]:
# RANDOM FOREST model
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=34,criterion='entropy',max_depth=5)
RF.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=5, n_estimators=34)

In [70]:
y_pred = RF.predict(x_test)
print(list(zip(y_test,y_pred)))

[(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 1), (1, 1), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),

In [71]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)
acc = accuracy_score(y_test,y_pred)
print('confusion matrix: \n',cm)
print('\nclassification report:\n',cr)
print('\naccuracy score: ',acc)

confusion matrix: 
 [[22576    77]
 [ 5490  2018]]

classification report:
               precision    recall  f1-score   support

           0       0.80      1.00      0.89     22653
           1       0.96      0.27      0.42      7508

    accuracy                           0.82     30161
   macro avg       0.88      0.63      0.66     30161
weighted avg       0.84      0.82      0.77     30161


accuracy score:  0.8154238917807765
